export const BASE_URL="http://localhost:8080";
export const DEPARTMENT_ADD="DEPARTMENT_ADD";
export const DEPARTMENT_UPDATE="DEPARTMENT_UPDATE";
export const DEPARTMENT_DELETE="DEPARTMENT_DELETE";
export const DEPARTMENT_BYID="DEPARTMENT_BYID";
export const DEPARTMENT_ALL="DEPARTMENT_ALL";