export const BASE_URL="http://localhost:8083";
export const RESERVATION_ADD="RESERVATION_ADD";
export const RESERVATION_ALL="RESERVATION_ALL"
export const LOGIN_RECEPTIONIST="LOGIN_RECEPTIONIST";
export const ADD_RECEPTIONIST="ADD_RECEPTIONIST";